### ISSUE TITLE
Alway getting 400 error from an Azure function registration

### ISSUE THREAD

**Issue by jhauppa2** [microsoftgraph/webjobs-webhooks-sample#3]
I have tried this sample a few different times, I always get this response to the call that attempts to create the web hook. It never works. The notificationUrl is an Azure Function configured as a WebHook

{
  "error": {
    "code": "InvalidRequest",
    "message": "Subscription validation request failed. Must respond with 200 OK to this request.",
    "innerError": {
      "request-id": "3d3f5faf-6c47-451a-8f34-697ae34e27be",
      "date": "2018-08-07T01:45:23"
    }
  }
}

The POST body is below. It looks OK given the few other examples and the docs out there.
 
{
"resource":"Users",
"changeType":"updated",
"clientState":"1234",
"notificationUrl":"https://testabcdefg.azurewebsites.net/api/GenericWebhookCSharp1?code=LZdLxCrjFNb6CiftXAk4OQ470c/b52Ta2ixbAj06iZsdaPELVvhoo8/Q==&clientId=default",
"expirationDateTime":"2018-08-09T01:46:07.1945409+00:00"
}

**Comment by jthake-msft** [comment]
@jasonjoh could you take a look at this?

**Comment by jhauppa2** [comment]
One key piece of information on this issue. I am attempting to run this against an Azure B2C tenant vs. Azure AD.

I tried against graph.microsoft.com -- both V1.0 and beta. Also tried against the older graph.windows.net. For graph.micorsoft.com I always get the same error -- it could be that Azure B2C does not support this webhook, but if it does then I would like to know what is wrong here.

**Comment by jasonjoh** [comment]
@jhauppa2 the error indicates that your webhook target is not responding properly to a validation request. See https://developer.microsoft.com/en-us/graph/docs/concepts/webhooks#notification-endpoint-validation for full details.

Basically when you post your subscription, Graph servers will contact your webhook with `?validationToken={TokenDefinedByMicrosoftGraph}`. Your webhook MUST respond with 200 OK and the validation token in the text/plain body.

**Comment by LeoGoGarcia** [comment]
I'm having the same problem today. 

Folowing the readme file it seams that the Azure Function created MUST be configured to handle ANONYMOUS requests. 

Could you please change it or give more instructions here? 


![capture](https://user-images.githubusercontent.com/24609659/47159062-4a463f80-d2ed-11e8-98e0-0d0634edaad3.GIF)

**Comment by jasonjoh** [comment]
The validation request does indeed come in with no auth header, so that sounds right.

**Comment by baywet** [comment]
Hi @jhauppa2 
Thanks for your question and sorry about the late reply.
We're archiving this sample as it is old and lacks maintenance.
If you have any questions about using the Microsoft Graph from Azure Functions or Azure Webjobs, please post those on [stackoverflow](https://stackoverflow.com/questions/tagged/microsoft-graph) with the microsoft-graph tag. We do have a dedicated triage system that's more reactive than issues follow up in samples repositories.
