### ISSUE TITLE
Requires an Update in the Steps 

### ISSUE THREAD

**Issue by velanchandru** [microsoftgraph/webjobs-webhooks-sample#4]
i'm following this article for getting notifications from Microsoft graph API through mail Subscriptions , i believe the steps given here bit mismatch to follow, since the Repo has not been updated for 2 years  , and i'm using Azure Developer Subscription ( Free), some help need to recreate or update the Steps

**Comment by baywet** [comment]
Hi @velanchandru 
Thanks for your question and sorry about the late reply.
We're archiving this sample as it is old and lacks maintenance.
If you have any questions about using the Microsoft Graph from Azure Functions or Azure Webjobs, please post those on [stackoverflow](https://stackoverflow.com/questions/tagged/microsoft-graph) with the microsoft-graph tag. We do have a dedicated triage system that's more reactive than issues follow up in samples repositories.
