### ISSUE TITLE
Do not receive notifications about user profile updates

### ISSUE THREAD

**Issue by otsomkalov** [microsoftgraph/webjobs-webhooks-sample#8]
I need to get notifications about user profiles updates in Azure B2C and handle them using Azure Functions HttpTrigger.

I followed this two guides:
https://docs.microsoft.com/en-us/graph/tutorials/change-notifications
https://github.com/microsoftgraph/webjobs-webhooks-sample

Result of both of them is successful subscription to user updates and successfully processed initial request with verification code, but when I'am editing user profile in my app I don't get any notifications about updates.

Subscription registration:
```
var subscription = new Subscription
            {
                ChangeType = "updated,deleted",
                NotificationUrl = "https://<ngrok_url>/persons",
                Resource = "Users",
                ExpirationDateTime = DateTime.UtcNow.AddMinutes(4229),
                ClientState = "SecretClientState"
            };
```
Function-handler of changes:
```
[FunctionName(nameof(GetChangesAsync))]
        public async Task<IActionResult> GetChangesAsync(
            [HttpTrigger(AuthorizationLevel.Function, "POST", Route = "persons")]
            HttpRequest request,
            ILogger logger)
        {
            if (request.Query.ContainsKey("validationToken"))
            {
                string validationToken = request.Query["validationToken"];

                return new OkObjectResult(validationToken);
            }

            using (var reader = new StreamReader(request.Body))
            {
                var content = await reader.ReadToEndAsync();

                var notifications = JsonConvert.DeserializeObject<Notifications>(content);

                if (notifications != null)
                {
                    foreach (var notification in notifications.Items)
                    {
                        logger.LogInformation(
                            $"Received notification: '{notification.Resource}', {notification.ResourceData?.Id}");
                    }
                }
            }

            return new OkResult();
        }
```
I expected to get notifiction every time when I'm editing user profile in Azure B2C -> Users.
Subscription ID: bd5ab06a-2f58-4015-af59-8b66d5539f54, Expiration: 09.08.2019 10:01:48 +00:00

**Comment by baywet** [comment]
Hi @otsomkalov 
Thanks for your question and sorry about the late reply.
We're archiving this sample as it is old and lacks maintenance.
If you have any questions about using the Microsoft Graph from Azure Functions or Azure Webjobs, please post those on [stackoverflow](https://stackoverflow.com/questions/tagged/microsoft-graph) with the microsoft-graph tag. We do have a dedicated triage system that's more reactive than issues follow up in samples repositories.
